### ISSUE TITLE
Empty messages in telegram

### ISSUE THREAD

**Issue by mchubarov** [Basheir/notificationTelegram#1]
Telegram receives empty messages about the order several times a day. How can I fix this?[
![Снимок экрана 2021-06-29 120923](https://user-images.githubusercontent.com/30138219/123747227-7e62c280-d8d4-11eb-8502-ddb5697b7f4b.jpg)
](url)

**Comment by mchubarov** [comment]
@BasheirHassan Please I am waiting for an answer

**Comment by BasheirHassan** [comment]
Hello
I will tomorrow help you
Can you connected with me whatsapp
My number
________________________________
من: mchubarov ***@***.***>
‏‏تم الإرسال: Wednesday, June 30, 2021 6:39:16 AM
إلى: BasheirHassan/notificationTelegram ***@***.***>
نسخة: Basheir Hassan ***@***.***>; Mention ***@***.***>
‏‏الموضوع: Re: [BasheirHassan/notificationTelegram] Empty messages in telegram (#1)


@BasheirHassan<https://github.com/BasheirHassan> Please I am waiting for an answer

**Comment by BasheirHassan** [comment]
don
